keepout_filter_mask_server:
  ros__parameters:
    use_sim_time: false
    topic_name: "keepout_filter_mask"
    frame_id: "map"
    yaml_filename: "Outdoor_new_mask.yaml"

keepout_costmap_filter_info_server:
  ros__parameters:
    use_sim_time: false
    type: 0
    filter_info_topic: "keepout_costmap_filter_info"
    mask_topic: "/keepout_filter_mask"
    base: 0.0
    multiplier: 1.0