planner_server:
  ros__parameters:
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_smac_planner/SmacPlanner2D"
      tolerance: 0.125 #​ បើ generated path មិនដល់គោលដៅអាចក្នុង tolerance X (m)
      downsample_costmap: false #​ មិនប្រើប្រាស់ downsample​​ ព្រោះយើង​ត្រូវការ precision ខ្ពស់
      downsampling_factor: 1 # No need to care since downsample_costmap is not used
      allow_unknown: false # មិនអនុញ្ញាតអោយរ៉ូបូតទៅទីតាំងដែលមិនបាន​ map
      max_iterations: 1000000 # Maximum number of search iterations before failing to limit compute time
      max_on_approach_iterations: 1000 #Maximum number of iterations after the search is within tolerance before returning approximate path with best heuristic if exact path is not found.
      max_planning_time: 2.0 #(s)
      cost_travel_multiplier: 3.0   #Cost multiplier to apply to search to steer away from high cost areas. Larger values will place in the center of aisles more exactly (if non-FREE cost potential field exists) but take slightly longer to compute. To optimize for speed, a value of 1.0 is reasonable. A reasonable tradeoff value is 2.0. A value of 0.0 effective disables steering away from obstacles and acts like a naive binary search A*.
      use_final_approach_orientation: false #If true, the last pose of the path generated by the planner will have its orientation set to the approach orientation, i.e. the orientation of the vector connecting the last two points of the path
      smoother:
        max_iterations: 1000  #The maximum number of iterations the smoother has to smooth the path, to bound potential computation.
        w_smooth: 0.3  #Weight for smoother to apply to smooth out the data points
        w_data: 0.2 #Weight for smoother to apply to smooth out the data points
        tolerance: 1.0e-10
        do_refinement: true
        refinement_num: 2

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 3.0 #(Hz)
      publish_frequency: 3.0 #(Hz)
      global_frame: map
      robot_base_frame: base_footprint
      transform_tolerance: 0.5 #(s)
      footprint: "[[0.25, 0.25], [-0.25, 0.25], [-0.25, -0.25], [0.25, -0.25]]" # all in (m)
      footprint_padding: 0.03   # extra 3cm buffer around footprint        
      resolution: 0.05 #m
      inf_is_valid: true
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer","stvl_layer","inflation_layer"]
      filters: ["keepout_filter"]

      keepout_filter:
        plugin: "nav2_costmap_2d::KeepoutFilter"
        enabled: True
        filter_info_topic: "/keepout_costmap_filter_info"

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 1.5
          clearing: true
          inf_is_valid: true
          marking: true
          data_type: "LaserScan"
          raytrace_max_range: 22.0 #m if no obstacle within range 0 to 3m clear
          raytrace_min_range: 0.05
          obstacle_max_range: 12.0 #m if there is an obstacle withtin range 0 to 3m mark
    
      stvl_layer:
        plugin: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
        enabled: true
        voxel_decay: 1.5              # Obstacle disappears after 0.5 seconds
        decay_model: 0                # Expires exactly at 0.5s — clean cutoff (LINEAR = 0)
        voxel_size: 0.05  ##Each 3D cube = 5cm × 5cm × 5cm
        track_unknown_space: false
        mark_threshold: 0  
        update_footprint_enabled: true  ##Clears voxels under the robot's footprint as it moves
        combination_method: 1
        origin_z: 0.0
        publish_voxel_map: true
        transform_tolerance: 0.5
        mapping_mode: false
        #map_save_duration: 60.0 # not neccessarily because mapping_mode is off

        ##Observation Source (Depth Camera)
        observation_sources: pointcloud
        pointcloud:
          data_type: PointCloud2
          topic: /camera/camera/depth/color/points
          sensor_frame: camera_link
          observation_persistence: 0.0
          expected_update_rate: 0.0
          inf_is_valid: true
          filter: "voxel"
          clear_after_reading: true
          voxel_min_points: 3
          marking: true
          clearing: true
          min_obstacle_height: 0.18
          max_obstacle_height: 1.8
          min_z: 0.18
          max_z: 1.8
          horizontal_fov_angle: 1.48702   # Exactly 85.2 degrees for D435
          vertical_fov_angle: 1.01229     # Exactly 58.0 degrees for D435
          decay_acceleration: 15.0     # Voxels expire 15× faster when not seen
          model_type: 0   ##Uses 3D ray tracing to clear free space
          obstacle_min_range: 0.05

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.7 #m
        cost_scaling_factor: 3.0  

      always_send_full_costmap: true
