slam_toolbox:
  ros__parameters:

    mode: localization

    # Your map file (point to .posegraph, BUT since yours is from map_saver we skip this)
    # slam_toolbox will subscribe to /map topic from map_server instead

    odom_frame: odom
    map_frame: map
    base_frame: base_footprint        # or base_link
    scan_topic: /scan
    use_sim_time: true

    do_loop_closing: false
    enable_interactive_mode: false
    map_start_at_dock: false

    resolution: 0.05
    max_laser_range: 20.0
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    tf_buffer_duration: 30.0